import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'About | Portfolio',
    description: 'Generated by create next app',
  }

export default function portfolio(){
    return <h1>About Page</h1> ;
}

