import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
    robots:"index, follow",
}

export default function About(){

    return <h1>About Page</h1> ;
}

