import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'About | Contacts',
    description: 'Generated by create next app',
  }

export default function contacts(){

    return <h1>Contacts</h1> ;
}

